# Generated by Django 5.1.5 on 2025-01-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_cover_image_alter_movie_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
